FROM ros:foxy-ros-base-focal
ARG USER=user
ARG DEBIAN_FRONTEND=noninteractive

RUN apt-get update && apt-get install -y --no-install-recommends \
    ros-foxy-desktop=0.9.2-1* vim nano \
    build-essential python3-colcon-common-extensions \
    python3-pip python3-rosdep \
    x11-apps libgl1-mesa-glx \
    && rm -rf /var/lib/apt/lists/*
    
WORKDIR /home/${USER}
